version: '3'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - ./volumes/mongodb:/data/db
  app:
    build: .
    depends_on:
      - mongodb
    environment:
      - PORT=4444
    ports:
      - 4444:4444
